Upgrade Forgelin dep to latest version
TeamWizardry/LibrarianLib pull request #46
Opened 2018-01-01 00:57 UTC by AlexCouch

2018-01-03 11:06 UTC, Bluexin requested changes
On a sidenote, the build has to be fixed ;p

2018-01-03 11:06 UTC, Bluexin commented on gradle.properties
> +kotlin_version=1.2.10
Forgelin is currently using kotlin 1.2.0

2018-01-03 11:06 UTC, Bluexin commented on build.gradle
> +//I'm also setting this to use the latest Forgelin cause the latest Forgelin has the latest kotlin
This comment is useless. We all know why Forgelin has to be updated ;p

2018-01-03 11:06 UTC, Bluexin commented on ConvertAssets.py
> -#!/usr/bin/python
This file doesn't hurt anyone by being there, if people prefer having their python script to convert CamelCase to snake_case, then so be it.
It does not add any setup time or anything for other people.

2018-01-03 13:25 UTC, yrsegal commented
Deleting ConvertAssets.py is a definite no-accept.

2018-01-06 04:34 UTC, yrsegal requested changes
Don't delete convertassets, don't comment extraneously

2018-01-06 07:21 UTC, Eladkay requested changes
Don't fix what ain't broke ay? That specifically refers to updating the gradle, which can not anything but issues, and don't delete the convert assets py.

2018-01-07 20:15 UTC, Bluexin commented
Duh, gh, y u no cloz

2018-01-07 20:15 UTC, closed without merging